version: "3"

services:
  kodi:
    image: vidiben/kodi
    devices:
      - /dev/dri
    environment:
      DISPLAY: "unix${DISPLAY:-:0}"
      XAUTHORITY: /home/me/.Xauthority
    ipc: host
    user: ${UID:-1000}:${GID:-1000}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $HOME/.Xauthority:/home/me/.Xauthority
      - /:/host:ro
